apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/metrics-server.yaml
  - ./manifests/namespace.yaml
  - ./manifests/app-configmap.yaml
  - ./manifests/app-secret.yaml
  - ./manifests/db/db-secret.yaml
  - ./manifests/db/db-configmap.yaml
  - ./manifests/db/db-deployment.yaml
  - ./manifests/db/db-service.yaml
  - ./manifests/app-deployment.yaml
  - ./manifests/app-service.yaml
  - ./manifests/app-hpa.yaml
  - ./manifests/db/db-seeder-job.yaml