apiVersion: apps/v1
kind: Deployment  # Responsável por gerenciar Pods e ReplicaSets
metadata:
  name: mecanica-dm-api
  namespace: mecanicadm
spec:
  replicas: 2 # Numero de pods que estarão ativos ao mesmo tempo
  selector:
    matchLabels:
      app: mecanica-dm-api # Diz para o controlador (Deployment) quais pods ele deve gerenciar
  template:
    metadata:
      labels:
        app: mecanica-dm-api # Tag que é aplicada a cada pod que é criado pelo deployment
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: [ 'sh', '-c', "until nc -zv postgres-db 5432; do echo waiting for postgres; sleep 2; done;" ]
      containers:
        - name: api
          image: guilhermemuchon/mecanica-dm-api
          imagePullPolicy: Always # Garante que o K8s baixe a versão mais nova do registro
          ports:
            - containerPort: 8080
          resources: # É necessário definir essa propriedade para o HPA saber quando escalar
            # Esses valores são os recursos padrão de cada replica gerada
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres-password
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MAIL_PORT
            - name: MAIL_SMTP_AUTH
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MAIL_SMTP_AUTH
            - name: MAIL_SMTP_STARTTLS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MAIL_SMTP_STARTTLS
            - name: BUDGET_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BUDGET_BASE_URL
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: MAIL_PASSWORD
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            # O K8s vai tentar 30 vezes, com intervalo de 10s (total 5 minutos)
            # dando tempo suficiente para a app subir antes de começar a liveness
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5