apiVersion: v1
# No ConfigMap podemos centralizar variáveis que não são secretas
kind: ConfigMap
metadata:
  name: db-config
  namespace: mecanicadm
data:
  DB_NAME: "mecanicadm"
  DB_HOST: "postgres-db"
  DB_PORT: "5432"
  DB_URL: "jdbc:postgresql://postgres-db:5432/mecanicadm"